version: '2'

services:
  db:
    image: mdillon/postgis:9.4
    environment:
     - POSTGRES_DB=amazontest_api_development
     - POSTGRES_USER=root

  dbtest:
    image: mdillon/postgis:9.4
    environment:
     - POSTGRES_DB=amazontest_api_test
     - POSTGRES_USER=root

  redis:
    image: redis

  sidekiq:
    depends_on:
     - db
     - dbtest
     - redis
    build: .
    command: bundle exec sidekiq
    volumes:
     - .:/app
    environment:
     - AMAZONTEST_API_REDIS_URL=redis://redis:6379/0

  web:
    depends_on:
     - db
     - dbtest
     - redis
    build: .
    command: bin/rails s --port 3000 --binding 0.0.0.0
    volumes:
     - .:/app
    ports:
     - '3000:3000'
